-- Drop and recreate the `mp` database
DROP DATABASE IF EXISTS mp;
CREATE DATABASE mp;
USE mp;

-- Create `image` table
CREATE TABLE image (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  IMAGE VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  CREATED_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE image ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0;
